### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by srtcdemir** [hthuwal/sign-language-gesture-recognition#1]
Hello Harish Chandra Thuwal.

I'm from Turkey.I am studying at a university and working on a project like your project.
But I'm new to this area and I do not know how to access the model to run the project. Can you help me with what I should do? 

My e-mail address is: srtc.demir@gmail.com, so please be very happy if you return.

**Comment by hthuwal** [comment]
Hi,
- You can go through the **Final Report.pdf** to get an idea about the methodology that we used. 
- Once you go through the files and the pdf, you'll get an idea about how to do it.
- I am planning to add a readme with steps in the future but it will take time.

You can learn basic steps about training inception(tensorflow) from [here](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html?index=..%2F..%2Findex#0)

**Comment by srtcdemir** [comment]
Hi Harish, thank you for your kind answer, i try to open and run the project, but i can't find data sets folder.Could you share data sets folders,please?

**Comment by hthuwal** [comment]
Reference to the dataset used is present in the Final Report.pdf. You can check that out.

**Comment by srtcdemir** [comment]
Thank you very much
