### ISSUE TITLE
DecodeJpeg/contents:0 is a tensor that does not exist in the graph

### ISSUE THREAD

**Issue by accaliwag05** [hthuwal/sign-language-gesture-recognition#12]
Hi, do you know why I keep getting this error? I followed everything. Thanks.

**Comment by Yuanhaotianbb** [comment]
Did you solve it?

**Comment by hthuwal** [comment]
I have pushed the updated code.

**Source of the bug you faced:** What used to be the DecodeJpeg operation is now named Placeholder
