### ISSUE TITLE
About the tensorboard graph pool_3 node

### ISSUE THREAD

**Issue by ukwai1203** [hthuwal/sign-language-gesture-recognition#13]
Hello, anyone can told me why I'm done retrain the inception v3 model, in my tensorboard graph does not exist pool_3 node. I use the retrain.py which is provided. Because of the absent of pool_3 node, the step 4 make_prediction_pool.py i cannot run successful, there always get an error:

KeyError: "The name 'pool_3:0' refers to a Tensor which does not exist. The operation, 'pool_3', does not exist in the graph."

**Comment by ukwai1203** [comment]
Even i run the make_predictions.py instead of make_predictions_pool.py, the result is showing "Error making prediction, continuing.", and in the end

0 0
Traceback (most recent call last):
  File "make_predictions.py", line 137, in <module>
    main()
  File "make_predictions.py", line 114, in main
    accuracy = get_accuracy(predictions, labels)
  File "make_predictions.py", line 95, in get_accuracy
    accuracy = correct / float(len(predictions))
ZeroDivisionError: float division by zero

**Comment by Lexicographical** [comment]
Hello. May I ask how you resolved this issue? I have the same error

**Comment by Lexicographical** [comment]
I retrained it with the inception model. The graph looks different but I still get the same error. 
I extracted the contents of the [Inception V3 file](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models) to a directory called "inception" in the root directory. Then, I executed the retrain command like so:
python retrain.py --bottleneck_dir=bottlenecks --model_dir=inception --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=majorData
is there anything I'm missing? Because when I run both make_predictions_pool.py and make_predictions.py I stil get the same errors.

**Comment by ukwai1203** [comment]
probably is the model problem, if not mistaken, the model I downloaded from
online is not something like you, you can try download other inception v3
model which you can found on github

Lexicographical <notifications@github.com> 于 2018年8月5日周日 上午10:26写道：

**Comment by ukwai1203** [comment]
because when the model is right one, then in your graph should have node
call pool_3, and the graph is procedure

钟子康 <ukwaielf@gmail.com> 于 2018年8月5日周日 上午10:39写道：

**Comment by Lexicographical** [comment]
The link I downloaded from was on GitHub from the official TensorFlow repo.
Is there another one?

**Comment by ukwai1203** [comment]
the model I used is download from some sign language gesture recognition
project, and that project also look like this project but that project have
provide the model and it can be use in this project.

Lexicographical <notifications@github.com> 于 2018年8月5日周日 上午10:41写道：

> The link I downloaded from was on GitHub from the official TensorFlow repo.
> Is there another one?
>

**Comment by Lexicographical** [comment]
Do you remember any keywords or something related that might help me find
the model you used?

**Comment by Lexicographical** [comment]
Oh I see. Thank you! I'll try looking for it as well

**Comment by ukwai1203** [comment]
you can try sign language gesture recognition github, the project almost
same as this project but in the code contain file named inception and in
the file have the model.

Lexicographical <notifications@github.com> 于 2018年8月5日周日 上午10:48写道：

> Do you remember any keywords or something related that might help me find
> the model you used?
>

**Comment by Lexicographical** [comment]
Ok thanks! I found a different model. The one I used was from 2016. The new
one I found is from 2015. I'm retraining it now. I'll update you in a few
hours when it's done. Thank you so much for the help! :)

**Comment by Lexicographical** [comment]
It's done retraining, but I still have the same error. What should be
inside the inception directory? Is it a .pb file? And should it have a
particular name?

**Comment by Lexicographical** [comment]
I went through retrain.py and it doesn't seem to have any option
"--model_dir" in its Argument Parser. Would it be possible that a different
retrain.py was used?

**Comment by persephone94** [comment]
have you solved the problem?  I got the same one .

**Comment by Lexicographical** [comment]
Hi! I decided to create a different repository with more comprehensive
instructions since many of the author's steps were unclear. Check it out
here: https://github.com/Lexicographical/Sign-Language-Gesture-Recognition
If you do enjoy it though, credit the original author. All I did was clean
up some parts

**Comment by persephone94** [comment]
@Lexicographical Thank you very much! It works! I think the original retrain.py has no BOTTLENECK_TENSOR_NAME = 'pool_3/_reshape:0'  
JPEG_DATA_TENSOR_NAME = 'DecodeJpeg/contents:0' 
so lead to the problem.

**Comment by Lexicographical** [comment]
Yeah. That was the problem I noticed as well. Had to go thru old projects
on GitHub to find a retrain.py that worked
