### ISSUE TITLE
make_predictions_pool.py pool_3:0 does not exist in the graph

### ISSUE THREAD

**Issue by Lexicographical** [hthuwal/sign-language-gesture-recognition#15]
I'm following your instructions for retraining the model. I'm also using the same Argentinian Sign Language dataset you cited. But when I tried running make_predictions_pool.py, it has an error saying that pool_3:0 does not exist in the graph.
I did:
"Video to Frame.py"
python retrain.py --bottleneck_dir=bottlenecks --model_dir=inception --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=majorData
python make_predictions_pool.py

But this terminates with the following error:
`Traceback (most recent call last):
  File "make_predictions_pool.py", line 89, in <module>
    main()
  File "make_predictions_pool.py", line 80, in main
    cnn_features = predict_on_frames(frames, batch)
  File "make_predictions_pool.py", line 28, in predict_on_frames
    pool_tensor = sess.graph.get_tensor_by_name('pool_3:0')
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3789, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3613, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3655, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'pool_3:0' refers to a Tensor which does not exist. The operation, 'pool_3', does not exist in the graph."
`
I tried inspecting the graph with TensorBoard and indeed, there is no Tensor called pool_3:0. But I followed all your instructions. Any help would be much appreciated! Thank you.

**Comment by ukwai1203** [comment]
In step 3 the model_dir missing, I can't find the model file here, I downloaded the model online and set path the dir of the model. I forgot which website I get the model from, you can try google for the model

**Comment by ukwai1203** [comment]
In the tensorgraph you can find out the graph generated is like a mind graph but the  graph should in a procedure form

**Comment by ukwai1203** [comment]
the keyword is inception v3 model

**Comment by hthuwal** [comment]
Code has been updated.

**Source of the bug you faced:** What used to be the `pool_3` operation is now named `module_apply_default/InceptionV3/Logits/GlobalPool`

**Comment by SANDEEPSURYAMUDAPAKA** [comment]
"The name 'pool_3:0' refers to a Tensor which does not exist. The operation, 'pool_3', does not exist in the graph."
I am also facing with the same issue can anyone tell me how to resolve this 
Thanks in advance
