### ISSUE TITLE
Trouble with make_prediction.py

### ISSUE THREAD

**Issue by abdulhaim** [hthuwal/sign-language-gesture-recognition#16]
Hi,
I am the step of running make_prediction.py after running retrain.py for the transfer learning step, but the program keeps going into the last if condition and prints("Error making prediction, continuing.")

After removing that print statement, I am getting this error: 

<img width="897" alt="screen shot 2018-10-08 at 4 19 35 pm" src="https://user-images.githubusercontent.com/13926336/46631645-08abdc80-cb16-11e8-9cd6-030073d143a1.png">

Would it possible to provide me with your email so I may forward a more detailed explanation of my problem? I would like to also speak to you about your methodology. Thanks!

**Comment by hthuwal** [comment]
Hi, I am pretty busy this week. Will Look into it when I get time.

You can find my email address on my profile page.

**Comment by hthuwal** [comment]
I have pushed the updated code.

Source of the bug you faced:

`What used to be the `DecodeJpeg` operation is now named `Placeholder`
