### ISSUE TITLE
Last step not working

### ISSUE THREAD

**Issue by vandana1212** [hthuwal/sign-language-gesture-recognition#19]
Hi, When I am running the last step using Approach 1 I am getting this error

rnn_eval.py predicted-frames-final_result-test.pkl non_pool.model
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
WARNING:tensorflow:From C:\Users\VANDANA\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Class Name      Numeric Label
green           0
opaque          1
red             2
Dataset shape:  (3, 201)
Traceback (most recent call last):
  File "C:\Users\VANDANA\Downloads\sign-language-gesture-recognition-master\rnn_eval.py", line 74, in <module>
    main(input_data_dump, num_frames_per_video, batch_size, labels, model_file)
  File "C:\Users\VANDANA\Downloads\sign-language-gesture-recognition-master\rnn_eval.py", line 28, in main
    size_of_each_frame = X.shape[2]
IndexError: tuple index out of range

What should I change ? I have kept only 3 categories in my dataset - opaque red and green. 

Any help would be appreciated

**Comment by hthuwal** [comment]
Hi Its difficult to infer the cause here. There seems to be some issue with the dump of test data. 

- Is the dump "predicted-frames-final_result-test.pkl" correct?
   -  Try printing X.shape.
   -  Try using it over the train data.

- Another source of error could be the fact the code assumes that 201 is the maximum number of frames per video.
    - You might need to change it to maximum number of frames.

**Comment by kinjalmistree** [comment]
> Hi, When I am running the last step using Approach 1 I am getting this error
> 
> rnn_eval.py predicted-frames-final_result-test.pkl non_pool.model
> curses is not supported on this machine (please install/reinstall curses for an optimal experience)
> WARNING:tensorflow:From C:\Users\VANDANA\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> Class Name Numeric Label
> green 0
> opaque 1
> red 2
> Dataset shape: (3, 201)
> Traceback (most recent call last):
> File "C:\Users\VANDANA\Downloads\sign-language-gesture-recognition-master\rnn_eval.py", line 74, in
> main(input_data_dump, num_frames_per_video, batch_size, labels, model_file)
> File "C:\Users\VANDANA\Downloads\sign-language-gesture-recognition-master\rnn_eval.py", line 28, in main
> size_of_each_frame = X.shape[2]
> IndexError: tuple index out of range
> 
> What should I change ? I have kept only 3 categories in my dataset - opaque red and green.
> 
> Any help would be appreciated

Hi, Could you solve this problem? I am getting the same error.
