### ISSUE TITLE
i am interested about you code 

### ISSUE THREAD

**Issue by sirak91** [hthuwal/sign-language-gesture-recognition#2]
i am trying to open your script put there is endless errors. i need to understand your code will. now i changed the video to frames and i made the data/labeled-frames-2.pkl file after that i don't now what to do ? and i think there is a problem in out.txt it's empty is that normal?

**Comment by sirak91** [comment]
can you tell me how i get the retrained_labels.txt please.

**Comment by hthuwal** [comment]
Wait for few days i'll try to update the readme with the steps by this weekend or  by early next week.

**Comment by hthuwal** [comment]
Hi, I've updated the readme writing as many details as I can. Now you should be able to run the code.

This is the best I can do to help you.

Happy Coding!!

Thanx :)

**Comment by rashedmahram** [comment]
thanks man i think now its going to work i am so glad for your help.
