### ISSUE TITLE
model file

### ISSUE THREAD

**Issue by raihan8025** [hthuwal/sign-language-gesture-recognition#22]
in step 4 whats the argument model file?

**Comment by hthuwal** [comment]
What readme are you referring to?

**Comment by raihan8025** [comment]
Sorry for not being clear. I was talking about model in step 4 which later I guessd would be output_graph,pb and it worked. Also I cant find the model file in step no. 5 inside the checkpoint folder which should be non_pool.model. Where is it stored?
