### ISSUE TITLE
issue about rnn_train.py

### ISSUE THREAD

**Issue by sunnymoon155** [hthuwal/sign-language-gesture-recognition#25]
Hi, thanks for your repo. I have a question about training RNN model. In rnn_train.py, there is a parameter name n_epoch=10, how should I change this epoch number if I use my own datasets? I found it's totally different if I set this parameter to 5,10,20. Should I save multiple models and test them all to get the best result?

**Comment by hthuwal** [comment]
Yes, n_epoch is a hyperparameter. You need to decide the optimum number of epochs for which the model should train (avoiding over/underfitting)
