### ISSUE TITLE
error in step 6 rnn_eval

### ISSUE THREAD

**Issue by nourach123** [hthuwal/sign-language-gesture-recognition#29]
No previous checkpoints of non_pool.model exist

Exiting..

This problem is showing up in step 6. I have 4 files created in the checkpoint folder named model_file.meta, model_file.index, model_file.data-00000-of-00001 and checkpoint after running rnn_train.py. But when executing rnn_eval, why cant it find the model file?

**Comment by testingshanu** [comment]
Try giving the absolute path to the model in the rnn_eval.
