### ISSUE TITLE
Testing using webcam

### ISSUE THREAD

**Issue by srtcdemir** [hthuwal/sign-language-gesture-recognition#3]
Can I do the testing through my webcam?

Is there a way to shorten the testing process? It's takes too long.

**Comment by geadalfa** [comment]
> Can I do the testing through my webcam?
> 
> Is there a way to shorten the testing process? It's takes too long.

Hey @srtcdemir did you successfully implement it?

**Comment by thanhsang298** [comment]
> > Can I do the testing through my webcam?
> > Is there a way to shorten the testing process? It's takes too long.
> 
> Hey @srtcdemir did you successfully implement it?

I'm also interested in..

**Comment by srtcdemir** [comment]
no i couldn't. I have not been interested in this project for a long time. @geadalfa
