### ISSUE TITLE
issue about predict_spatial

### ISSUE THREAD

**Issue by sunnymoon155** [hthuwal/sign-language-gesture-recognition#30]
Hi, thanks for the code, and I have a question about predictions generation. If i put all frames, for example, frames_1, frames_2 ... frames_50 of **video1** and frames_1, frames_2 ... frames_50 of **video2** into a folder(even more frames from more videos), when I do predict_spatial.py(num_frames_per_video=50), the order is not frames1-frames50 but out-of-order, so the predictions([[0.9,0.1],'label1'],[[0.6,0.4],'label1'],....) is not the correct order even not from the same video.

**Comment by hthuwal** [comment]
Yeah, you are right. But predict_spatial is used to create an intermediate representation (probability distribution or output of pool layer) for each frame using inception. So the order in which the frames are processed is not important. 

The order of frames matters while training LSTM.

**Comment by sunnymoon155** [comment]
> Yeah, you are right. But predict_spatial is used to create an intermediate representation (probability distribution or output of pool layer) for each frame using inception. So the order in which the frames are processed is not important.
> 
> The order of frames matters while training LSTM.

Yes, but is there any sort function in your rnn_train.py code? I din't find it, and if I use the intermediate representation(pkl file) to do training, the order have not been sorted which means the input of LSTM training is still out-of-order.

**Comment by sunnymoon155** [comment]
@hthuwal
