### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by berylyellow** [hthuwal/sign-language-gesture-recognition#33]
@hthuwal Hi, thanks for your repo. I followed your steps but meet some errors:
When I retrain the Inception v3 model by " python3 retrain.py --bottleneck_dir=bottlenecks --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=train_frames"
It mentons that "urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>". What happens? Could you help me?

**Comment by hthuwal** [comment]
Seems like you are not connected to the internet. Make sure you can connect to the internet from the terminal where you are running the code.

**Comment by berylyellow** [comment]
It didnt work. I can download things and surf the internet，but I dont know why I met this problem.

**Comment by berylyellow** [comment]
![2019-05-26 18-12-22 的屏幕截图](https://user-images.githubusercontent.com/36025537/58380305-17320000-7fe2-11e9-9ed8-953fc990d3b7.png)

**Comment by hthuwal** [comment]
Are you using some proxy to connect to the network. If so have you configured the terminal to use it?

This doesn't seem to be a project specific issue.
