### ISSUE TITLE
Blank frames detected

### ISSUE THREAD

**Issue by vandana1212** [hthuwal/sign-language-gesture-recognition#34]
I am testing using LSA 64 and have downloaded the preprocessed version as available on their website. When I am running on your code, the train frames are detecting all black images. I cannot see any difference between the frames. 

Kindly help me. Am I doing something wrong ? I am new to opencv and hence confused.

**Comment by hthuwal** [comment]
Hi, I tried running the code on a sample video from LSA64 video. This is one of the frames that is being extracted. The hand is segmented out and then the image is turned grayscale.

| Extracted Frame  | Hand Segmentation | Final Grayscale Frame |
|---------|-----------|-----------|
|![001_001_001_frame_0 jpegorg](https://user-images.githubusercontent.com/15616911/58149275-d489c400-7c7f-11e9-8ade-951f436b6d71.jpeg)|![001_001_001_frame_0 jpegseg](https://user-images.githubusercontent.com/15616911/58149295-ecf9de80-7c7f-11e9-9c9f-1947ce82ea70.jpeg)|![001_001_001_frame_0](https://user-images.githubusercontent.com/15616911/58149158-588f7c00-7c7f-11e9-9b09-28e3bc678dab.jpeg)|
