### ISSUE TITLE
Model of 'rnn.tflearn'

### ISSUE THREAD

**Issue by andi00123456** [hthuwal/sign-language-gesture-recognition#5]
Hi,
      I have the new issue of your rnn_train.py. I believe it's in 27 line: model.load('checkpoints/rnn.tflearn')
      I have checked all of codes and didn't find where does this model be created. Because when I was running rnn_train.py file, It's gaving me error which is about unsuccessful TensorSliceReader constructor: Failed to find any matching files for /.../checkpoints/rnn.tflearn. 
      Please help me with how to deal with this problem.
Thanks

**Comment by hthuwal** [comment]
Did you create the "checkpoints" folder in the root directory. Its there in the Readme

**Comment by andi00123456** [comment]
I did create the 'checkpoints' folder before running run_train.py.
Can you tell me which code create model of rnn.tflearn? Cause I didn't find it

**Comment by srtcdemir** [comment]
I solved this problem by deleting the 27th line in rnn_train.

**Comment by hthuwal** [comment]
That line was for when you have already trained the model and wanted to retrain it. 
Also i have pushed the fix
