### ISSUE TITLE
run rnn_train.py fail!

### ISSUE THREAD

**Issue by zy486at189cn** [hthuwal/sign-language-gesture-recognition#6]
nice job!

I use your code to train a model.meet one problem.
The model have three classes,I use three kinds videos to train it. name action1,action2,action3.
I success to 
python "Video To Frame.py" 
python retrain.py --bottleneck_dir=bottlenecks --model_dir=inception --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=majorData
python make_predictions.py
python make_predictions_pool.py

But when run rnn_train.py,it fail. just as this:
1action2 2
action1 1
action3 0
Total dataset size: 82
Traceback (most recent call last):
  File "rnn_train.py", line 52, in <module>
    main(filename, frames, batch_size, num_classes, input_length)
  File "rnn_train.py", line 13, in main
    filename, frames, num_classes, input_length, True)
  File "/home/stockerc/project/sign-language-gesture-recognition/rnn_utils.py", line 62, in get_data
    X = X.reshape(-1, num_frames, input_length)
ValueError: cannot reshape array of size 49446 into shape (201,64)
How do I define the follow:
    input_length = 64 ?
    frames = 201
    batch_size = 32
    num_classes = 64
in the rnn_train.py  file!
which means   input_length ?

Thanks you!

**Comment by zy486at189cn** [comment]
When I use mode 2 and modify rnn_train.py just as this:
    filename = 'data/cnn-features-frames-1.pkl'
    input_length = 2048
    #filename = 'data/predicted-frames-1.pkl'
    #input_length = 64
It can be trained!

**Comment by andi00123456** [comment]
@zy486at189cn 
Hi,
   After you finish training model. Does the test running perfect or not? Cause when I was running test steps, they just said InvalidArgument Error. Do you know how to fix it?

**Comment by hthuwal** [comment]
> nice job!
> 
> I use your code to train a model.meet one problem.
> The model have three classes,I use three kinds videos to train it. name action1,action2,action3.
> I success to
> python "Video To Frame.py"
> python retrain.py --bottleneck_dir=bottlenecks --model_dir=inception --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=majorData
> python make_predictions.py
> python make_predictions_pool.py
> 
> But when run rnn_train.py,it fail. just as this:
> 1action2 2
> action1 1
> action3 0
> Total dataset size: 82
> Traceback (most recent call last):
> File "rnn_train.py", line 52, in 
> main(filename, frames, batch_size, num_classes, input_length)
> File "rnn_train.py", line 13, in main
> filename, frames, num_classes, input_length, True)
> File "/home/stockerc/project/sign-language-gesture-recognition/rnn_utils.py", line 62, in get_data
> X = X.reshape(-1, num_frames, input_length)
> ValueError: cannot reshape array of size 49446 into shape (201,64)
> How do I define the follow:
> input_length = 64 ?
> frames = 201
> batch_size = 32
> num_classes = 64
> in the rnn_train.py file!
> which means input_length ?
> 
> Thanks you!

input_length denotes the size of the representation of each frame. In the first case that would be equal to the number of classes.

**Comment by hthuwal** [comment]
Scripts have been updated to automatically handle this based on how many classes are present in the training folder.

**Comment by kinjalmistree** [comment]
> nice job!
> 
> I use your code to train a model.meet one problem.
> The model have three classes,I use three kinds videos to train it. name action1,action2,action3.
> I success to
> python "Video To Frame.py"
> python retrain.py --bottleneck_dir=bottlenecks --model_dir=inception --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=majorData
> python make_predictions.py
> python make_predictions_pool.py
> 
> But when run rnn_train.py,it fail. just as this:
> 1action2 2
> action1 1
> action3 0
> Total dataset size: 82
> Traceback (most recent call last):
> File "rnn_train.py", line 52, in
> main(filename, frames, batch_size, num_classes, input_length)
> File "rnn_train.py", line 13, in main
> filename, frames, num_classes, input_length, True)
> File "/home/stockerc/project/sign-language-gesture-recognition/rnn_utils.py", line 62, in get_data
> X = X.reshape(-1, num_frames, input_length)
> ValueError: cannot reshape array of size 49446 into shape (201,64)
> How do I define the follow:
> input_length = 64 ?
> frames = 201
> batch_size = 32
> num_classes = 64
> in the rnn_train.py file!
> which means input_length ?
> 
> Thanks you!

Hello, Did you get the solution of this? I am getting same error.
