### ISSUE TITLE
Can i know which dataset used?

### ISSUE THREAD

**Issue by ukwai1203** [hthuwal/sign-language-gesture-recognition#9]
I have downloaded the dataset from the website, but there is not contain any material that told me about which word belong to the video.

**Comment by hthuwal** [comment]
![image](https://user-images.githubusercontent.com/15616911/40406157-39dcc482-5e7d-11e8-9769-9a6a7e8330b0.png)

Its there on their website.

**Comment by ukwai1203** [comment]
I download the raw version and the pre-process version, but in the file didn't contain any material that can help me differentiate which word belong to the video  @hthuwal

**Comment by ukwai1203** [comment]
follow this table? @hthuwal

**Comment by hthuwal** [comment]
Can you show me the folder structure of the downloaded data?

**Comment by ukwai1203** [comment]
i found the file already, thanks. But i saw there in the table consists two
red so how can i open two folder named red at the same time, i change one
of them to reds will it lead to an error?

**Comment by ukwai1203** [comment]
I will try rest of the code tomorrow, if i counter any error i will email
you, thanks for help.

**Comment by ukwai1203** [comment]
Good morning sir, may I know where can I find/generate
the labeled-frames-2.pkl file? Sorry for disturb.
